## 1. Import Library serta Menggabungkan Keenam Dataset menjadi Satu

In [1]:
# Import library awal yang dibutuhkan
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
plt.style.use("seaborn")
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error

### 1.1. Dataset Bulan Januari 2021

In [2]:
# Load dataset
data_januari = pd.read_csv("Volume Pengangkutan Sampah Di Kali Sungai Situ Waduk Bulan Januari Tahun 2021.csv", 
                           encoding="latin-1")
data_januari.tail()

,bulan,titik_lokasi,kecamatan,wilayah,panjang/luas,satuan_panjang/luas,tanggal,volume_sampah_perhari(m3)
54338,1,Kali Cakung Drain (Jembatan Tinggi-Perbatasan ...,Cakung,Jakarta Timur,800,m,31,-
54339,1,PHB Rawa Teratai,Cakung,Jakarta Timur,700,m,31,-
54340,1,PHB Rawa Gelam III,Cakung,Jakarta Timur,1000,m,31,-
54341,1,PHB Metropos KIP,Cakung,Jakarta Timur,1000,m,31,-
54342,1,PHB Warung Jengkol,Cakung,Jakarta Timur,400,m,31,2

In [3]:
data_januari.shape

(54343, 8)

### 1.2. Dataset Bulan Februari 2021

In [4]:
# Read dataset
data_februari = pd.read_csv("volume-pengangkutan-sampah-di-kali-sungai-situ-waduk-bulan-februari-tahun-2021.csv", 
                            encoding="latin-1")
data_februari.tail()

,bulan,titik_lokasi,kecamatan,wilayah,panjang/luas,satuan_panjang/luas,tanggal,volume_sampah_perhari(m3)
49247,2,Kali Cakung Drain (Jembatan Tinggi-Perbatasan ...,Cakung,Jakarta Timur,800,m,28,-
49248,2,PHB Rawa Teratai,Cakung,Jakarta Timur,700,m,28,-
49249,2,PHB Rawa Gelam III,Cakung,Jakarta Timur,1000,m,28,-
49250,2,PHB Metropos KIP,Cakung,Jakarta Timur,1000,m,28,-
49251,2,PHB Warung Jengkol,Cakung,Jakarta Timur,400,m,28,-

In [6]:
data_februari.shape

(49252, 8)

### 1.3. Dataset Bulan Maret 2021

In [7]:
# Read dataset
data_maret = pd.read_csv("volume-pengangkutan-sampah-di-kali-sungai-situ-waduk-bulan-maret-tahun-2021.csv",
                         encoding="latin-1")
data_maret.head()

,bulan,titik_lokasi,kecamatan,wilayah,panjang/luas,satuan_panjang/luas,tanggal,volume_sampah_perhari(m3)
0,3,Kali / Sungai Sentiong - Ruas Dewi Sri,Johar Baru,Jakarta Pusat,464,m,1,3
1,3,Kali / Sungai Sentiong - Ruas Abapon,Johar Baru,Jakarta Pusat,464,m,1,4
2,3,Kali / Sungai Sentiong - JL Tanah Tinggi,Johar Baru,Jakarta Pusat,464,m,1,4
3,3,Kali / Sungai Sentiong Jl.Galur - Pombensin,Johar Baru,Jakarta Pusat,606,m,1,5
4,3,Kali / Sungai Sentiong - Jl. Timah,Johar Baru,Jakarta Pusat,310,m,1,6

### 1.4. Dataset Bulan April 2021

In [8]:
# Read dataset
data_april = pd.read_csv("volume-pengangkutan-sampah-di-kali-sungai-situ-waduk-bulan-april-tahun-2021.csv",
                         encoding="latin-1")
data_april.head()

,bulan,titik_lokasi,kecamatan,wilayah,panjang/luas,satuan_panjang/luas,tanggal,volume_sampah_perhari(m3)
0,4,Kali / Sungai Sentiong - Ruas Dewi Sri,Johar Baru,Jakarta Pusat,464,m,1,3
1,4,Kali / Sungai Sentiong - Ruas Abapon,Johar Baru,Jakarta Pusat,464,m,1,3
2,4,Kali / Sungai Sentiong - JL Tanah Tinggi,Johar Baru,Jakarta Pusat,464,m,1,3
3,4,Kali / Sungai Sentiong Jl.Galur - Pombensin,Johar Baru,Jakarta Pusat,606,m,1,3
4,4,Kali / Sungai Sentiong - Jl. Timah,Johar Baru,Jakarta Pusat,310,m,1,4

In [9]:
data_maret.shape

(54715, 8)

### 1.5. Dataset Bulan Mei 2021

In [10]:
# Read dataset
data_mei = pd.read_csv("volume-pengangkutan-sampah-di-kali-sungai-situ-waduk-bulan-mei-tahun-2021.csv",
                       encoding="latin-1")
data_mei.head()

,bulan,titik_lokasi,kecamatan,wilayah,panjang/luas,satuan_panjang/luas,tanggal,volume_sampah_perhari(m3)
0,5,Kali / Sungai Sentiong - Ruas Dewi Sri,Johar Baru,Jakarta Pusat,464,m,1,3
1,5,Kali / Sungai Sentiong - Ruas Abapon,Johar Baru,Jakarta Pusat,464,m,1,3
2,5,Kali / Sungai Sentiong - JL Tanah Tinggi,Johar Baru,Jakarta Pusat,464,m,1,3
3,5,Kali / Sungai Sentiong Jl.Galur - Pombensin,Johar Baru,Jakarta Pusat,606,m,1,4
4,5,Kali / Sungai Sentiong - Jl. Timah,Johar Baru,Jakarta Pusat,310,m,1,4

In [11]:
data_mei.shape

(54870, 8)

### 1.6. Dataset Bulan Juni 2021

In [12]:
# Read dataset
data_juni = pd.read_csv("volume-pengangkutan-sampah-di-kali-sungai-situ-waduk-bulan-juni-tahun-2021.csv",
                        encoding="latin-1")
data_juni.head()

,bulan,titik_lokasi,kecamatan,wilayah,panjang/luas,satuan_panjang/luas,tanggal,volume_sampah_perhari(m3)
0,6,Kali / Sungai Sentiong - Ruas Dewi Sri,Johar Baru,Jakarta Pusat,464,m,1,3
1,6,Kali / Sungai Sentiong - Ruas Abapon,Johar Baru,Jakarta Pusat,464,m,1,4
2,6,Kali / Sungai Sentiong - JL Tanah Tinggi,Johar Baru,Jakarta Pusat,464,m,1,4
3,6,Kali / Sungai Sentiong Jl.Galur - Pombensin,Johar Baru,Jakarta Pusat,606,m,1,4
4,6,Kali / Sungai Sentiong - Jl. Timah,Johar Baru,Jakarta Pusat,310,m,1,5

In [13]:
data_juni.shape

(53130, 8)

### 1.7. Menggabungkan Keenam DataFrame menjadi Satu

In [14]:
"""
Membuat variabel dataframe untuk menampung hasil penggabungan 
keempat dataframe (dataframe penjualan sayur di bulan Juni - September 2021)
"""
data_sampah = [data_januari, data_februari, data_maret, data_april, data_mei, data_juni]

"""
Menggabungkan dataframe "data_sayur" yang berisi penampungan data dari 
keempat dataframe ke dalam satu kesatuan dataframe yang bernama "data_penjualan_sayur_mayur"
"""
data_prediksi_sampah = pd.concat(data_sampah)

data_prediksi_sampah.tail()

,bulan,titik_lokasi,kecamatan,wilayah,panjang/luas,satuan_panjang/luas,tanggal,volume_sampah_perhari(m3)
53125,6,Kali Cakung Drain (Jembatan Tinggi-Perbatasan ...,Cakung,Jakarta Timur,800,m,30,-
53126,6,PHB Rawa Teratai,Cakung,Jakarta Timur,700,m,30,-
53127,6,PHB Rawa Gelam III,Cakung,Jakarta Timur,1000,m,30,2
53128,6,PHB Metropos KIP,Cakung,Jakarta Timur,1000,m,30,-
53129,6,PHB Warung Jengkol,Cakung,Jakarta Timur,400,m,30,-

## 3. Data Preprocessing

In [17]:
# Menghapus jarak spasi pada kolom dataset
data_prediksi_sampah.columns = data_februari.columns.str.replace(" ", "")

In [18]:
# Mengubah format penamaan kolom dari yang semula huruf kecil menjadi huruf gabungan (huruf besar & kecil)
data_prediksi_sampah = data_prediksi_sampah.rename(str.title, axis="columns")
data_prediksi_sampah.columns

Index(['Bulan', 'Titik_Lokasi', 'Kecamatan', 'Wilayah', 'Panjang/Luas',
       'Satuan_Panjang/Luas', 'Tanggal', 'Volume_Sampah_Perhari(M3)'],
      dtype='object')

In [19]:
# Menghapus karakter yang berada di kolom "Panjang/Luas" seperti pada data 3500/70 yang dapat dilihat pada tahapan sebelumnya
data_prediksi_sampah["Panjang/Luas"] = data_prediksi_sampah["Panjang/Luas"].str.replace(r"\D", "")

In [21]:
# Mengahapus karakter "-" di kolom "Volume_Sampah_Perhari(M3)" dengan nilai NaN
data_prediksi_sampah["Volume_Sampah_Perhari(M3)"] = data_prediksi_sampah["Volume_Sampah_Perhari(M3)"].replace("-", np.nan)

data_prediksi_sampah.tail()

,Bulan,Titik_Lokasi,Kecamatan,Wilayah,Panjang/Luas,Satuan_Panjang/Luas,Tanggal,Volume_Sampah_Perhari(M3)
53125,6,Kali Cakung Drain (Jembatan Tinggi-Perbatasan ...,Cakung,Jakarta Timur,800,m,30,NaN
53126,6,PHB Rawa Teratai,Cakung,Jakarta Timur,700,m,30,NaN
53127,6,PHB Rawa Gelam III,Cakung,Jakarta Timur,1000,m,30,2
53128,6,PHB Metropos KIP,Cakung,Jakarta Timur,1000,m,30,NaN
53129,6,PHB Warung Jengkol,Cakung,Jakarta Timur,400,m,30,NaN

In [22]:
# Mengubah tipe data di kolom "Panjang/Luas" dari string menjadi float
data_prediksi_sampah[["Panjang/Luas"]] = data_prediksi_sampah[["Panjang/Luas"]].apply(pd.to_numeric)

In [23]:
# Mengubah tipe data pada kolom "Volume_Sampah_Perhari(M3)" dari string menjadi float
data_prediksi_sampah["Volume_Sampah_Perhari(M3)"] = pd.to_numeric(data_prediksi_sampah["Volume_Sampah_Perhari(M3)"], 
                                                                  errors="coerce")

data_prediksi_sampah.dtypes

Bulan                          int64
Titik_Lokasi                  object
Kecamatan                     object
Wilayah                       object
Panjang/Luas                 float64
Satuan_Panjang/Luas           object
Tanggal                        int64
Volume_Sampah_Perhari(M3)    float64
dtype: object

In [ ]:
# Mengganti nilai NaN yang ada disetiap kolom di dataframe data_februari dengan nilai mean
mean = data_prediksi_sampah.mean()
data_prediksi_sampah = data_prediksi_sampah.replace(np.nan, mean)

data_prediksi_sampah.isnull().sum()